"use strict";
exports.__esModule = true;
exports.NodeFeature = void 0;
var NodeFeature;
(function (NodeFeature) {
    NodeFeature["ARR"] = "arr";
    NodeFeature["ATOMIC"] = "atomic";
    NodeFeature["BINARY"] = "binary";
    NodeFeature["CONDITIONAL"] = "conditional";
    NodeFeature["DECLARATION"] = "declaration";
    NodeFeature["EMPTY"] = "empty";
    NodeFeature["FUNC"] = "func";
    NodeFeature["KEYWORD"] = "keyword";
    NodeFeature["LITERAL"] = "literal";
    NodeFeature["LOGIC_DOOR"] = "logicDoor";
    NodeFeature["BIT_DOOR"] = "bitDoor";
    NodeFeature["LOOP"] = "loop";
    NodeFeature["REGEX"] = "regex";
    NodeFeature["TERNARY"] = "ternary";
})(NodeFeature = exports.NodeFeature || (exports.NodeFeature = {}));
